services:
  db: # Mongo replica set
    build: ./mongodb_rs
    restart: always
    environment:
      - MONGO_REPLICA_PORT=27017
      - MONGO_REPLICA_HOST=localhost
      - MONGO_INITDB_DATABASE=mongo
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - '27017:27017'